version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: install_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: root